helloffice/src/main/java/com/kh/helloffice/board/controller/BoardController.java
helloffice/src/main/webapp/WEB-INF/views/board/add-board.jsp
helloffice/src/main/webapp/WEB-INF/views/board/board.jsp
helloffice/src/main/webapp/WEB-INF/views/common/footer.jsp
helloffice/src/main/webapp/WEB-INF/views/common/head.jsp
helloffice/src/main/webapp/WEB-INF/views/common/header.jsp

전체게시판 레이아웃 구현
- 게시판 목록 페이지
- 게시글 작성 페이지
- 컨트롤러 연결
resolved: #10

💄 전체게시판 레이아웃 구현

---

helloffice/src/main/java/com/kh/helloffice/board/controller/BoardController.java
helloffice/src/main/java/com/kh/helloffice/board/dao/BoardDao.java
helloffice/src/main/java/com/kh/helloffice/board/dao/BoardDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/board/entity/BoardDto.java
helloffice/src/main/java/com/kh/helloffice/board/entity/PostDto.java
helloffice/src/main/java/com/kh/helloffice/board/service/BoardService.java
helloffice/src/main/java/com/kh/helloffice/board/service/BoardServiceImpl.java
helloffice/src/main/resources/mybatis/board-mapper.xml
helloffice/src/main/resources/mybatis/mybatis-config.xml
helloffice/src/main/webapp/WEB-INF/views/board/add-post.jsp
helloffice/src/main/webapp/WEB-INF/views/board/board.jsp
helloffice/src/main/webapp/WEB-INF/views/board/edit-post.jsp
helloffice/src/main/webapp/WEB-INF/views/board/post.jsp
helloffice/src/main/webapp/WEB-INF/views/common/header.jsp
helloffice/src/main/webapp/WEB-INF/views/template.jsp
helloffice/src/main/webapp/WEB-INF/web.xml

게시판 CRUD 구현
- 게시글 작성
- 게시글 목록 조회
- 게시글 상세 조회
- 게시글 수정
- 게시글 삭제
- 앞으로 구현해야 할 것
- 게시글 권한 설정
- 팀별 게시판 메뉴 경로 설정 
- 게시글 검색 (카테고리, 이름)
- 페이징
resolved: #12

Feature #12 게시판 CRUD 구현

---

helloffice/src/main/java/com/kh/helloffice/work/controller/WorkMainController.java
helloffice/src/main/webapp/WEB-INF/views/common/header.jsp
helloffice/src/main/webapp/WEB-INF/views/work/workMain.jsp

:lipsticks: 근무, 휴가 페이지 구현

---

helloffice/src/main/java/com/kh/helloffice/workflow/controller/WorkflowController.java
helloffice/src/main/webapp/WEB-INF/views/common/header.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/allDoc.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/myDoc.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/wfForm.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/wfNav.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/wfSideNav.jsp

- 워크플로우 태그,양식 레이아웃 구현
- 
- 워크플로우 태그,양식 레이아웃 구현(80% 정도)
- 
resolved: #

💄워크플로우 태그,양식 레이아웃 구현

---

helloffice/src/main/java/com/kh/helloffice/member/controller/LoginContoller.java
helloffice/src/main/java/com/kh/helloffice/member/dao/MemberDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/member/entity/MemberDto.java
helloffice/src/main/java/com/kh/helloffice/member/service/MemberServiceImpl.java
helloffice/src/main/resources/mybatis/member-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/common/header.jsp
helloffice/src/main/webapp/WEB-INF/views/member/login.jsp

Feature #2

---

helloffice/src/main/java/com/kh/helloffice/work/controller/WorkMemberController.java
helloffice/src/main/webapp/WEB-INF/views/work/workMain.jsp
helloffice/src/main/webapp/WEB-INF/views/work/workMember.jsp
helloffice/src/main/webapp/resources/assets/css/workCss/workMain.css
helloffice/src/main/webapp/resources/assets/css/workCss/workMember.css

완료
구성원 스케줄 UI
근무 유형, 반복 일정 등록Modal
1차 완료. 기능 넣으면서, 그리고 마무리로 3차까지 진행할 듯
resolved: #33

💄근무 페이지 구현 완료

---

helloffice/src/main/webapp/WEB-INF/views/main.jsp

UI, 현재 날짜/시간 출력 완료
Main 페이지라 조심스럽게 했습니다.
resolved: #4

💄메인페이지 출근 카드 UI 완료

---

helloffice/src/main/java/com/kh/helloffice/member/controller/MemberContoller.java
helloffice/src/main/java/com/kh/helloffice/member/dao/MemberDao.java
helloffice/src/main/java/com/kh/helloffice/member/dao/MemberDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/member/entity/MemberDto.java
helloffice/src/main/java/com/kh/helloffice/member/service/MemberServiceImpl.java
helloffice/src/main/resources/mybatis/member-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/common/header.jsp
helloffice/src/main/webapp/WEB-INF/views/member/join.jsp

회원가입 프로필사진 구현중
파일 저장 위치 &  changeName = null 인 것 & {loginEmp.changeName}으로 프로필 사진 가져오기 > 고민해보기
resolved: #

🚧회원가입 프로필사진 구현중

---

helloffice/src/main/webapp/WEB-INF/views/workflow/wfForm.jsp

- 워크플로우 레이아웃 js 미적용 수정
- 모달, 각종 팝업창 미적용 수정
- 태그관리 레이아웃 수정
resolved: #44

💄워크플로우 레이아웃 js 미적용 수정

---

helloffice/src/main/java/com/kh/helloffice/reservation/controller/ReservationManagementController.java
helloffice/src/main/webapp/WEB-INF/views/common/header.jsp
helloffice/src/main/webapp/WEB-INF/views/reservation/management.jsp
helloffice/src/main/webapp/resources/assets/css/style.css

예약 관리 페이지 UI 레이아웃 구현
- 사이드바 예약 탭에 관리 페이지로 가는 아이콘 추가
- 예약 관리 페이지 레이아웃 구현
- 자산 관리 탭
- 예약 신청 관리 탭
- 관리자 설정 탭
- 각 탭에 대한 상세 설정 페이지 모달로 구현
resolved: #45

Style #45 예약 관리 페이지 UI 레이아웃

---

helloffice/src/main/java/com/kh/helloffice/reservation/controller/ReservationController.java
helloffice/src/main/java/com/kh/helloffice/reservation/controller/ReservationManagementController.java
helloffice/src/main/java/com/kh/helloffice/reservation/dao/ReservationDao.java
helloffice/src/main/java/com/kh/helloffice/reservation/dao/ReservationDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/reservation/dao/ReservationManagementDao.java
helloffice/src/main/java/com/kh/helloffice/reservation/dao/ReservationManagementDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/reservation/entity/AssetDto.java
helloffice/src/main/java/com/kh/helloffice/reservation/service/ReservationManagementService.java
helloffice/src/main/java/com/kh/helloffice/reservation/service/ReservationManagementServiceImpl.java
helloffice/src/main/java/com/kh/helloffice/reservation/service/ReservationService.java
helloffice/src/main/java/com/kh/helloffice/reservation/service/ReservationServiceImpl.java
helloffice/src/main/resources/mybatis/mybatis-config.xml
helloffice/src/main/resources/mybatis/reservation-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/common/head.jsp
helloffice/src/main/webapp/WEB-INF/views/reservation/management.jsp
helloffice/src/main/webapp/WEB-INF/views/reservation/reservation.jsp

예약 자산 추가 및 목록 조회 기능 구현
- 예약 관리 페이지에서 예약 자산 추가
- 예약 관리 페이지에서 자산 목록 조회
- 예약 페이지에서 자산 목록 조회 
resolved: #49

Feature #49 예약 자산 추가 기능

---

helloffice/src/main/java/com/kh/helloffice/workflow/controller/WorkflowController.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/WorkflowDao.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/WorkflowDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/workflow/entity/TagDto.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/WorkflowService.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/WorkflowServiceImpl.java
helloffice/src/main/resources/mybatis/workflow-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/workflow/wfForm.jsp

- 태그 관련 기능 구현 완료
- 태그 추가, 수정, 삭제 기능
- 태그 목록 보기는 태그관리탭, 태그배너, 워크플로우 만들기에서 볼 수 있게끔 하기
resolved: #47

✨태그 기능 구현 완료

---

helloffice/src/main/java/com/kh/helloffice/reservation/controller/ReservationController.java
helloffice/src/main/java/com/kh/helloffice/reservation/controller/ReservationManagementController.java
helloffice/src/main/java/com/kh/helloffice/reservation/dao/ReservationDao.java
helloffice/src/main/java/com/kh/helloffice/reservation/dao/ReservationDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/reservation/dao/ReservationManagementDao.java
helloffice/src/main/java/com/kh/helloffice/reservation/dao/ReservationManagementDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/reservation/entity/ReservationDto.java
helloffice/src/main/java/com/kh/helloffice/reservation/service/ReservationManagementService.java
helloffice/src/main/java/com/kh/helloffice/reservation/service/ReservationManagementServiceImpl.java
helloffice/src/main/java/com/kh/helloffice/reservation/service/ReservationService.java
helloffice/src/main/java/com/kh/helloffice/reservation/service/ReservationServiceImpl.java
helloffice/src/main/resources/mybatis/reservation-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/reservation/management.jsp
helloffice/src/main/webapp/WEB-INF/views/reservation/reservation.jsp

예약 신청 관리, 예약취소 기능 구현
- 예약 관리 -> 예약 신청 관리 -> 신청 목록 조회
- 예약 관리 -> 예약 신청 관리 -> 예약 설정 버튼 클릭 시 예약 정보 조회
- 예약 관리 -> 예약 신청 관리 -> 설정 -> 예약 상태 변경 구현
- 예약 취소 기능 구현
- 
resolved: #64

Feature #64 예약 신청 관리, 예약취소

---

helloffice/src/main/webapp/WEB-INF/views/board/board.jsp
helloffice/src/main/webapp/WEB-INF/views/board/post.jsp

게시글 수정 작성자만 가능하도록 권한 설정
- 게시글 수정 작성자만 가능하도록 권한 설정
- 게시글 등록 버튼 url 연결 수정
resolved: #78

Feature #78 게시글 수정 권한 설정

---

helloffice/src/main/java/com/kh/helloffice/reservation/controller/ReservationManagementController.java
helloffice/src/main/java/com/kh/helloffice/reservation/dao/ReservationManagementDao.java
helloffice/src/main/java/com/kh/helloffice/reservation/dao/ReservationManagementDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/reservation/service/ReservationManagementService.java
helloffice/src/main/java/com/kh/helloffice/reservation/service/ReservationManagementServiceImpl.java
helloffice/src/main/resources/mybatis/reservation-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/reservation/management.jsp

예약 자산 수정 및 삭제
- 예약 자산 수정 구현
- 예약 자산 삭제 구현
resolved: #82

Feature #82 예약 자산 수정 및 삭제

---

helloffice/src/main/webapp/WEB-INF/views/reservation/reservation.jsp

예약 페이지 UI/UX 개선
- 예약 완료 후 예약 폼 비우기
- 내 예약 목록 예약 상태별 배지 색 변경
resolved: #86

Style #86 예약 페이지 UI/UX 개선

---

helloffice/src/main/java/com/kh/helloffice/board/controller/BoardController.java
helloffice/src/main/java/com/kh/helloffice/board/entity/PageVo.java
helloffice/src/main/java/com/kh/helloffice/board/service/BoardService.java
helloffice/src/main/java/com/kh/helloffice/board/service/BoardServiceImpl.java
helloffice/src/main/resources/mybatis/board-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/board/board.jsp

게시판 검색 기능
- 카테고리별 검색
- 제목으로 검색
resolved: #87

Feature #87 게시판 검색 기능

---

helloffice/src/main/java/com/kh/helloffice/todo/controller/ToDoController.java
helloffice/src/main/java/com/kh/helloffice/todo/dao/ToDoDao.java
helloffice/src/main/java/com/kh/helloffice/todo/dao/ToDoDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/todo/entity/ToDoDto.java
helloffice/src/main/java/com/kh/helloffice/todo/service/ToDoService.java
helloffice/src/main/java/com/kh/helloffice/todo/service/ToDoServiceImpl.java
helloffice/src/main/resources/mybatis/mybatis-config.xml
helloffice/src/main/resources/mybatis/todo-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/main.jsp

할일(투두리스트) 기능 추가
- 할일, 요청 UI 분리
- 할일 CRUD 구현
resolved: #93

Feature #93 할일(투두리스트)

---

helloffice/src/main/java/com/kh/helloffice/workflow/controller/WorkflowController.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/WorkflowDao.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/WorkflowDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/workflow/entity/AllCusDto.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/WorkflowService.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/WorkflowServiceImpl.java
helloffice/src/main/resources/mybatis/workflow-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/workflow/wfForm.jsp
helloffice/src/main/webapp/resources/assets/css/workflowCss/wfForm.css
helloffice/src/main/webapp/resources/assets/js/workflowJs/wfForm.js

- 워크플로우 데이터받기, 각 커스텀 테이블 생성
- 커스텀 DB테이블 생성, mapper 작성(양식첨부, 승인 제외)
resolved: #84

✨워크플로우 데이터받기, 각 커스텀 테이블 생성

---

helloffice/src/main/java/com/kh/helloffice/work/controller/WorkController.java
helloffice/src/main/java/com/kh/helloffice/work/dao/WorkDao.java
helloffice/src/main/java/com/kh/helloffice/work/dao/WorkDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/work/service/WorkService.java
helloffice/src/main/java/com/kh/helloffice/work/service/WorkServiceImpl.java
helloffice/src/main/resources/mybatis/work-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/main.jsp
helloffice/src/main/webapp/WEB-INF/views/work/adminWorkMain.jsp

관리자용 근무 검색 기능 추가
resolved: #100

Feature #100 근무 검색 기능 추가

---

helloffice/src/main/java/com/kh/helloffice/workflow/controller/WorkflowController.java
helloffice/src/main/resources/mybatis/workflow-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/workflow/wfForm.jsp
helloffice/src/main/webapp/resources/assets/js/workflowJs/wfForm.js

- 워크플로우 양식 DB테이블 대거 수정
- 워크플로우 양식 DB테이블 대거 수정
- 슬랙 GIT 채널에 업데이트 예정
resolved: #97

🗃️워크플로우 양식 DB테이블 대거 수정

---

helloffice/src/main/java/com/kh/helloffice/work/controller/OffController.java
helloffice/src/main/java/com/kh/helloffice/work/controller/WorkController.java
helloffice/src/main/java/com/kh/helloffice/work/dao/WorkDao.java
helloffice/src/main/java/com/kh/helloffice/work/dao/WorkDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/work/entity/WorkPageVo.java
helloffice/src/main/java/com/kh/helloffice/work/service/WorkService.java
helloffice/src/main/java/com/kh/helloffice/work/service/WorkServiceImpl.java
helloffice/src/main/resources/mybatis/work-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/work/adminOff.jsp
helloffice/src/main/webapp/WEB-INF/views/work/adminWorkMain.jsp
helloffice/src/main/webapp/WEB-INF/views/work/off.jsp
helloffice/src/main/webapp/WEB-INF/views/work/offPayBack.jsp
helloffice/src/main/webapp/WEB-INF/views/work/useDoOff.jsp
helloffice/src/main/webapp/WEB-INF/views/work/workMain.jsp

연차관련 ui추가
관리자 근무 수정/삭제 페이지 페이징구현
resolved: #104

Style #104 연차관련 UI 및 페이징 기능 추가

---

helloffice/src/main/java/com/kh/helloffice/work/controller/OffController.java
helloffice/src/main/java/com/kh/helloffice/work/dao/OffDao.java
helloffice/src/main/java/com/kh/helloffice/work/dao/OffDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/work/entity/OffDto.java
helloffice/src/main/java/com/kh/helloffice/work/service/OffService.java
helloffice/src/main/java/com/kh/helloffice/work/service/OffServiceImpl.java
helloffice/src/main/resources/mybatis/mybatis-config.xml
helloffice/src/main/resources/mybatis/off-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/work/adminOff.jsp
helloffice/src/main/webapp/WEB-INF/views/work/view.jsp
helloffice/src/main/webapp/WEB-INF/views/work/write.jsp

✨휴가생성 CRUD 기능추가

---

helloffice/src/main/java/com/kh/helloffice/chat/controller/ChatController.java
helloffice/src/main/webapp/WEB-INF/views/chat/chat.jsp
helloffice/src/main/webapp/WEB-INF/views/chat/room.jsp
helloffice/src/main/webapp/WEB-INF/views/common/header.jsp

Firebase를 이용하여 1:1 채팅 기능 구현
- 메뉴바 메신저 탭 추가
- 채팅방 생성
- 1:1 실시간 대화
- 내가 참여한 채팅방 목록 조회
resolved: #99

Feature #99 메신저 기능

---

helloffice/src/main/java/com/kh/helloffice/workflow/controller/WorkflowController.java
helloffice/src/main/webapp/WEB-INF/views/workflow/wfForm.jsp
helloffice/src/main/webapp/resources/assets/js/workflowJs/wfForm.js

- 사원전체조회를 통한 승인자 선택 구현
- 사원 전체 리스트를 갖고 와서 select의 option에 넣기
- 선택한 option들을 승인단계태그 안에 append
resolved: #115

✨사원전체조회를 통한 승인자 선택 구현

---

helloffice/src/main/webapp/WEB-INF/views/chat/chat.jsp
helloffice/src/main/webapp/WEB-INF/views/chat/room.jsp
helloffice/src/main/webapp/WEB-INF/views/main.jsp

대화할 상대 검색하여 조회 가능
메인화면 메시지 카드 구현
- 검색어를 입력하여 사원 목록 조회
- 채팅방에서 엔터 입력시 메시지 전송
- 메인화면 메시지 카드에 최신 채팅목록 3개 조회
- 메시지 클릭시 해당 채팅창 열림
resolved: #119

Feature #119 대화 상대 검색 및 메인화면 메시지 카드 구현

---

helloffice/src/main/java/com/kh/helloffice/workflow/controller/WorkflowController.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/WorkflowDao.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/WorkflowDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/workflow/entity/WfFormDto.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/WorkflowService.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/WorkflowServiceImpl.java
helloffice/src/main/resources/mybatis/workflow-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/workflow/sam2.html
helloffice/src/main/webapp/WEB-INF/views/workflow/wfForm.jsp
helloffice/src/main/webapp/resources/assets/js/workflowJs/wfForm.js

- 승인테이블 추가, 양식 테이블 수정, 승인 UI 오류 해결
- 승인테이블 추가
- 양식 테이블 수정 : 양식pk를 넣은 테이블 추가함
- 승인 UI 오류 해결
resolved: #117

✨승인테이블 추가, 양식 테이블 수정, 승인 UI 오류 해결

---

helloffice/src/main/java/com/kh/helloffice/board/entity/PostDto.java
helloffice/src/main/resources/mybatis/board-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/board/board.jsp
helloffice/src/main/webapp/WEB-INF/views/common/header.jsp

부서별 게시판 구현
- 로그인 유저가 속한 부서 게시판 메뉴 탭 추가
- 부서별 게시판 구현
resolved: #129

Feature #129 부서별 게시판

---

helloffice/src/main/java/com/kh/helloffice/workflow/controller/WorkflowController.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/WorkflowDao.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/WorkflowDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/workflow/entity/WfDocDto.java
helloffice/src/main/java/com/kh/helloffice/workflow/entity/WfFormDto.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/WorkflowService.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/WorkflowServiceImpl.java
helloffice/src/main/resources/mybatis/workflow-mapper.xml
helloffice/src/main/webapp/resources/assets/js/workflowJs/wfForm.js

- 문서, 문서승인관련 테이블 작성, 데이터 담기
- 문서 테이블 작성
- 문서승인관련 테이블 작성
- 데이터 담기
resolved: #134

✨문서, 문서승인관련 테이블 작성, 데이터 담기

---

helloffice/src/main/java/com/kh/helloffice/UserInterceptor.java
helloffice/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml

세션 없을시 로그인 화면으로 리다이렉트
- 인터셉터를 이용하여 세션 없을시 로그인 화면으로 리다이렉트
resolved: #

💄 세션 없을시 로그인 화면으로 리다이렉트

---

helloffice/src/main/java/com/kh/helloffice/hr/controller/HrController.java
helloffice/src/main/java/com/kh/helloffice/hr/dao/HrDao.java
helloffice/src/main/java/com/kh/helloffice/hr/dao/HrDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/hr/entity/InsaNoteDto.java
helloffice/src/main/java/com/kh/helloffice/hr/service/HrService.java
helloffice/src/main/java/com/kh/helloffice/hr/service/HrServiceImpl.java
helloffice/src/main/resources/mybatis/hr-mapper.xml
helloffice/src/main/resources/mybatis/mybatis-config.xml
helloffice/src/main/webapp/WEB-INF/views/hr/memberPage.jsp
helloffice/src/main/webapp/WEB-INF/views/hr/myPage.jsp
helloffice/src/main/webapp/WEB-INF/views/hr/teamList.jsp
helloffice/src/main/webapp/WEB-INF/views/hr/teamReport.jsp
helloffice/src/main/webapp/resources/assets/js/hrJs/hrJs.js

관리자 등급나눠서 화면에서 수정할 수 있는 버튼 지정함.
마이페이지 휴가, 문서 파트 일부 수정 밑 링크 연결
인사노트 기능 구현 (1/2) 
- 등록 가능, 삭제 에러
이메일 화면 아무리 생각해도 안이쁨..
resolved: #145

✨ - 인사 노트 기능 + (마이페이지 일부 수정 & 관리자 등급별 화면 버튼 변경)

---

helloffice/src/main/java/com/kh/helloffice/workflow/controller/DocController.java
helloffice/src/main/java/com/kh/helloffice/workflow/controller/WorkflowController.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/DocDao.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/DocDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/workflow/entity/WfDocDto.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/DocService.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/DocServiceImpl.java
helloffice/src/main/resources/mybatis/mybatis-config.xml
helloffice/src/main/resources/mybatis/workflow-mapper.xml
helloffice/src/main/resources/mybatis/workflowDoc-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/workflow/allDoc.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/wfForm.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/wfNav.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/wfSideNav.jsp
helloffice/src/main/webapp/resources/assets/js/workflowJs/allDoc.js
helloffice/src/main/webapp/resources/assets/js/workflowJs/wfForm.js

-  문서 전체 조회, 상세 조회
-  문서 전체 조회, 상세 조회
resolved: #140

Feature #140 문서 전체 조회, 상세 조회

---

helloffice/src/main/java/com/kh/helloffice/member/service/MemberServiceImpl.java
helloffice/src/main/java/com/kh/helloffice/reservation/controller/ReservationManagementController.java

회원가입, 예약관리자 권한 오류 수정
- 회원가입 프로필 등록 삭제
- 예약 관리자 권한 없을시 발생하는 에러 수정
resolved: #

Hotfix #3 버그 수정

---

helloffice/src/main/webapp/WEB-INF/views/common/header.jsp
helloffice/src/main/webapp/WEB-INF/views/member/login.jsp
helloffice/src/main/webapp/resources/assets/css/style.css

ui 자잘한 수정
- 로그인 화면 수정
- 프로필 사진 기본 아이콘
resolved: #

Hotfix #4 ui 자잘한 수정

---

helloffice/src/main/resources/mybatis/workflow-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/workflow/allDoc.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/wfForm.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/wfNav.jsp
helloffice/src/main/webapp/resources/assets/js/workflowJs/allDoc.js
helloffice/src/main/webapp/resources/assets/js/workflowJs/wfForm.js

- 관리자와 일반사원 구분, 부서별 구분해서 상세조회
- 관리자와 일반사원 구분, 부서별 구분해서 상세조회
- 기타 오류 해결
resolved: #

✨관리자와 일반사원 구분, 부서별 구분해서 상세조회

---

helloffice/src/main/java/com/kh/helloffice/work/controller/WorkController.java
helloffice/src/main/resources/mybatis/work-mapper.xml
helloffice/src/main/resources/mybatis/workEdit-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/work/workDetail.jsp

근무 수정 관련 기능 추가
모두 고생 많으셨습니다.
resolved: #156

Feature #156 근무 수정 관련 기능 추가

---

helloffice/src/main/java/com/kh/helloffice/workflow/controller/DocController.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/DocDao.java
helloffice/src/main/java/com/kh/helloffice/workflow/dao/DocDaoImpl.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/DocService.java
helloffice/src/main/java/com/kh/helloffice/workflow/service/DocServiceImpl.java
helloffice/src/main/resources/mybatis/workflow-mapper.xml
helloffice/src/main/resources/mybatis/workflowDoc-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/common/header.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/allDoc.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/myDoc.jsp
helloffice/src/main/webapp/WEB-INF/views/workflow/wfNav.jsp
helloffice/src/main/webapp/resources/assets/js/workflowJs/myDoc.js

- 승인자 별 승인과 거절 기능 구현
resolved: #

✨승인자 별 승인과 거절 기능 구현(미완성)

---

helloffice/src/main/java/com/kh/helloffice/hr/controller/MyPageController.java
helloffice/src/main/resources/mybatis/workflow-mapper.xml
helloffice/src/main/webapp/WEB-INF/views/hr/memberPage.jsp
helloffice/src/main/webapp/WEB-INF/views/hr/myPage.jsp
helloffice/src/main/webapp/resources/assets/js/workflowJs/wfForm.js

Feature #151

---

helloffice/src/main/webapp/WEB-INF/views/workflow/myDoc.jsp
helloffice/src/main/webapp/resources/assets/js/workflowJs/wfForm.js

- 불필요한 코드 삭제 및 깃충돌 해결
- 브랜치 닫고 새 브랜치에 작업할 예정
resolved: #152

Feature #152 불필요한 코드 삭제 및 깃충돌 해결
